name: Laptop ipxe image boot builder

on:
  push:
    branches: 
      - '*'
    tags:
      - '!v*'
  pull_request:
    branches: 
     - '*'

jobs:

  make-test-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install isohybrid 
      run: sudo apt-get install syslinux-utils

    - name: Run make
      run: cd image-builder && make iso
