name: Laptop ipxe image boot builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  source_checkout:

    runs-on: ubuntu-latest

    steps:
    - name: check the code out
      uses: actions/checkout@master

  build:

    runs-on: ubuntu-latest

    steps:
    - name: check some stuff
      run: pwd

    - name: check some stuff
      run: export

    - name: check some stuff
      run: ls -al

    - name: Login to docker hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build :latest
      run: docker build -t ${GITHUB_REPOSITORY}:latest Dockerfile-worker

    - name: Push to docker hub :latest
      uses: actions-hub/docker@master
      with:
        args: push ${GITHUB_REPOSITORY}:latest
