name: Laptop ipxe image boot builder

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  make-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install isohybrid 
      run: sudo apt-get install syslinux-utils

    - name: Run make
      run: cd image-builder && make iso
