name: Build iso image without release

on:
  push:
    branches: 
      - '*'
    tags:
      - '!v*'
  pull_request:
    branches: 
     - '*'

jobs:

  make-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install isohybrid 
      run: sudo apt-get install syslinux-utils

    - name: Run make
      run: cd image-builder && sudo make iso

    - name: List dirs
      run: ls -lR
