name: Build iso with release 

on:
  push:
    tags:
      - 'v*'

jobs:

  make-iso:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install isohybrid 
      run: sudo apt-get install syslinux-utils

    - name: Run make
      run: cd image-builder && sudo make iso

    - name: Set CHANNEL
      run: echo ::set-env name=CHANNEL::$(grep "CHANNEL" ./image-builder/configs/current_release | cut -d'=' -f2)
    
    - name: Set DATE
      run: echo ::set-env name=DATE::$(date +'%Y-%m-%d')
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload channel asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  
        asset_path: ./image-builder/dist/${{ env.CHANNEL }}/${{ env.CHANNEL}}.zip
        asset_name: ${{ env.CHANNEL }}-${{ env.DATE }}.zip
        asset_content_type: application/zip

    - name: Upload boot.ipxe 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}  
        asset_path: ./image-builder/dist/${{ env.CHANNEL }}/boot.ipxe
        asset_name: ${{ env.DATE }}-boot.ipxe
        asset_content_type: application/zip
